language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make travis
env:
  global:
  - secure: Sb6GJDbLCRJwzb8iyWhfDDPDlIejZKZVZYIGV6V7Gx4NSeJCSuYC7wKru5l1HHqATGsBBtqbdHCP2sViWj5MJYnwUgmJQoT4QJ/kvk4LawV941S51iNNLNnaEtHnrWZeoeQO5S7XbMQ5baoQYvNVO07MAkhl0JLlCaP7cDllDGCdd/xulLTsuM2pra+sKAugfj+CFHRu85s2CxC43eyspub4j41AgkprPOgeYUcaATcXwUydPh76HXMaF9rYu//GkwLoHxmb3V5aqa5KpJWC6eENfpRn+bOHUNqYUffLLlPxKZwuviUImk+rN5z/FJueIit3B649XIVMLpycLQlzn9o0COZ+nUROrAxi3FSgzDh5Tu/3YJEjB3Lz6foGGJOtQF+IW2/MMbkNG87aZgt8QaDHcshGmqpDrLxffLI0TIdmzU6d9L0gsLFzUz6qCPIXj/plZUobKWDlqoN8yxyBY6dPWHfIb/d7lspqfy1XDXv9ApfSUhBzVSRtskjyJkbgwS3snHC6kP/z3FXdP2h9jl3rX6PUzQJPj9szAjoujMmcZktw9rOki2pQQf7uSox8rE4awi2oCeMLtg+zc9jRGfwp2v0qG0B0zWUyP1oDiPThFFwa/+ZU7nY6X2ETdmfTOmD9qq3E5ryJdGt5JXGVEhJHFWo1WDeUxH32fsmiO8k=
