language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- make travis
env:
  global:
    secure: RGOKI5ZSZtuLgZJ9Ud/QU2PzX9EAWlZWYgMqBq6mjc+9bQR0X8Sr1jlaKoi494oW7o+lPAl156wbA5qCy8HZzeTz8wdDIpXDrxVH+jMA54tDW6iGsj9w0J6EZF1ImGiiA+4UFVBSYzMLlIttrB/LWE5PugK9epfdwTrGBX430KUXNGbi596Nql2QonXfMMVAvQDhUjT/i+gI/EYR7qOw05xgg3kzteJY1ngduA12/5uHU2idV+gQO0/wxByFIHZ4M5MCTNfzuW4EITpQcfhXsqQTx0Ha3cVdE5vWVn5flhwJYfU7j8DsRIjWFb11JJyXob2+1ilqXxYaRaAs51DMWHVVPm+kYLOYnUQoZggX6R6fMq0Hgy8a1IfSjBVYiU9Y4UcHms4iOqE9tV2EM74K2cqB5vgfzKWfM7RSMWTZ9KKh1mZBdJLwj5DxTdtkasoaB3ErLJOCJIrW1unnwuW37fwYCbzfzqeKZ9U/HdUVO2glH8Opfwbb+6fAM1vMlbrqJZpRDIAHpVOxRua6cxJkeZ5AyJz6gea4kKJvw9UPmwQm2DQoMky7BNmx7vnxUPKZg1SqsPybwWY/j0wlpJO2fCTLEOJVlDuS0pTRAjD+DJqa4yMbzz+OcvO2OqNjJW4Xn33FP8YK7/raMckP5ijECLWFbMocEXeSQxpiRNE3OmM=
