baseURL = "/"
languageCode = "pt-br"
title = "Blog do Ely"

theme = 'mainroad'
generateTaxonomyList = true
sortTaxonomyAlphabetical = true
authorname = "Élysson MR"
favicon = "img/favicon.ico"

DisqusShortname = "elyssonmr-blog"
googleAnalytics = "G-JVL66Z9J82"

# MARKUP
[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    style = "solarized-dark"

# MAIN MENU

[[menu.main]]
  Name = "Home"
  URL = "/"
  weight = -10

[Params]
  # TOC
  toc = true

  # SIDEBAR
  sidebarHeader = "Bio"
  sidebarText = """Desenvolvedor de Software que já trabalhou em todo o ciclo de
  desenvolvimento. Hoje estou focando mais em arquitetura e quero compartilhar
  com vocês um pouco do que eu aprendi na minha tragetória.

  Um dos meus objetivos é montar cursos em meu canal do youtube. Peço que se
  inscreva para ficar por dentro das novidades
    """
  github = "https://github.com/elyssonmr"
  gitlab = ""
  twitter = "https://twitter.com/elyssonmr"
  linkedin = "https://linkedin.com/in/elyssonmr"
  youtube = "https://www.youtube.com/@elyssonmr"
  sidebarMenuEnabled = false
  twitter_cards = true
  readmore = true
  pager = true
  post_meta = ["date"]
  customCSS = ["css/custom.css"]

[Params.logo]
  image = "img/favicon.ico"
  title = "Blog do Ely"
  subtitle = "Um pouco do pouco que conheço"

[Params.thumbnail]
  visibility = ["list", "post"]

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.search]
  cached = false # activate cache if true
  url = "https://google.com/search"
  [Params.widgets.search.input]
    name = "sitesearch"
    pre = ""

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  twitter = "elyssonmr"
  linkedin = "elyssonmr"
  github = "elyssonmr"
  gitlab = "elyssonmr"

[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/@elyssonmr"
  icon = "svg/youtube.svg"
  rel = "noopener noreferrer" # Set to false to remove the rel attribute

[[Params.widgets.social.custom]]
  title = "Minha página"
  icon = "svg/author.svg"
  url = "http://elyssonmr.com"

sidebarRecentLimit = 5
